// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB12Dz959GRn1CVddlbF7rwT_w-JS82X78',
    appId: '1:230971078730:web:449864245701bb8c53ceb3',
    messagingSenderId: '230971078730',
    projectId: 'youandi-5b3cd',
    authDomain: 'youandi-5b3cd.firebaseapp.com',
    storageBucket: 'youandi-5b3cd.appspot.com',
    measurementId: 'G-XM5TT9YWB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbsIttGtCLsU0wynEzBhqHjiro-p6-wdo',
    appId: '1:230971078730:android:83d14a6a62704bcb53ceb3',
    messagingSenderId: '230971078730',
    projectId: 'youandi-5b3cd',
    storageBucket: 'youandi-5b3cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA735lDty5BHciKeaDU1MifubUomgKE4A8',
    appId: '1:230971078730:ios:d8ae7b2aed94b0f853ceb3',
    messagingSenderId: '230971078730',
    projectId: 'youandi-5b3cd',
    storageBucket: 'youandi-5b3cd.appspot.com',
    iosClientId: '230971078730-dj0lgjgfosvm9g6p81i8n97rdh5sp91l.apps.googleusercontent.com',
    iosBundleId: 'com.example.youandiDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA735lDty5BHciKeaDU1MifubUomgKE4A8',
    appId: '1:230971078730:ios:d8ae7b2aed94b0f853ceb3',
    messagingSenderId: '230971078730',
    projectId: 'youandi-5b3cd',
    storageBucket: 'youandi-5b3cd.appspot.com',
    iosClientId: '230971078730-dj0lgjgfosvm9g6p81i8n97rdh5sp91l.apps.googleusercontent.com',
    iosBundleId: 'com.example.youandiDiary',
  );
}
